### ISSUE TITLE
Encoding issue with PRONTO metadata input file

### ISSUE THREAD

**Issue by tinavisnovska** [InPreD/PRONTO#33]
Until v1.2.0 we did not have any issue with diacritic, but in v1.2.0 we've started to experience "ø" from the PRONTO metadata file to be printed in the output report as "Ã¸" and I suspect that other Norwegian specific characters would get modified too. We use utf-8 encoding when creating PRONTO metadata file. 

Just an idea: maybe specifying the PRONTO metadata file encoding in the Config/configure_PRONTO.ini file could resolve this issue for all the nodes (as the used encoding can be node specific but not too likely to change between different sequencing runs)?

**Comment by xiaoliz0** [comment]
This is caused by the previous pull request from gertrudeln (https://github.com/InPreD/PRONTO/pull/28). Remove the "ISO-8859-1" from PRONTO.py script fixed the same issue in OUS. I will include the options of encoding into configure file. This will be done in the branch develop_OUS and ask for confirmation before releasing.

**Comment by xiaoliz0** [comment]
The new function is implemented in develop_OUS.
